export interface Product {
    productId: number,
    productName: string,
    productCode: number,
    operatingSystem: string,
    description: string,
    basePrice: number,
    prgCode: number,
    lastVersion: string,
    lastReleaseDate: string,
    maxNumberOfUsers: number,
    variants: Array<any>,
    versions: Array<any>,
    packets: Array<any>,
    agreementCode: string,
    agreementUrl: string,
    agreementDesc: string,
    productNameShortcut: string,
    productNameDescription: string,
    productUrl: string,
    packetDescription: string,
    variantDescription: string,
    eduLicenseDescription: string,
    requiredProducts: Array<any>,
    productImage: string
  }